### ISSUE TITLE
Scripts cannot be modified

### ISSUE THREAD

**Issue by MPK1** [galexrt/docker-sinusbot#10]
Hey there,
unfortunately I can't modify the scripts because they aren't mounted in /sinusbot/data. Is it possible to add a volume for the scripts?

**Comment by galexrt** [comment]
I added a volume for the scripts. The volume is located at `/sinusbot/scripts`.

***

Please note that this fixes the "wrong" data directory path, that I just found out about!
The data directory is now located at `/sinusbot/data` and not `/data` anymore.
For compatibility reasons, the "old" directory `/data` will still continue to work.

**Comment by galexrt** [comment]
The images have been built and updated.

***

Don't forget to pull the image to update it:
For the quay.io image run:
```
docker pull quay.io/galexrt/sinusbot:latest
```
For the Docker Hub image run:
```
docker pull galexrt/sinusbot:latest
```

**Comment by galexrt** [comment]
Sorry for the inconveniences!
Issues with the TeamSpeak Client have now also been fixed.

**Comment by MPK1** [comment]
It looks like there's a little problem with yt-dl...

I get get the following error since I pulled the new Image:
```
2017/01/25 12:02:28 exit status 127 youtube-dl not found
```

**Comment by galexrt** [comment]
Can you please re-pull the image (with the command above). Report back if it's working now.

And if it's still not working then, please post the output of the following command(s):
```
docker images quay.io/galexrt/sinusbot:latest
```

**Comment by MPK1** [comment]
The output of
`docker images quay.io/galexrt/sinusbot:latest`
was just
`REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE`

I also tried

`docker images galexrt/sinusbot:latest`

and get

```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
galexrt/sinusbot    latest              b703a86681eb        30 minutes ago      524.4 MB
```

**Comment by galexrt** [comment]
You are using the image from the Docker Hub. You need to run `docker pull galexrt/sinusbot:latest`.

**Comment by MPK1** [comment]
That's exactly what I just did when you said the I have to re-pull the image.

**Comment by galexrt** [comment]
You already stopped and deleted the container and re-run it?

**Comment by MPK1** [comment]
Yes, but is it necessary to delete also the files?

I did:
```
docker pull ...
docker stop sinusbot
docker rm sinusbot
docker run --name sinusbot ...
```

**Comment by galexrt** [comment]
No you shouldn't need to delete the files.
Can you post your full run command.

**Comment by MPK1** [comment]
```docker run --name sinusbot2 -d -v /opt/docker/sinusbot2/data:/sinusbot/data -v /opt/docker/sinusbot2/scripts:/sinusbot/scripts -p 8088:8087 galexrt/sinusbot:latest```

The name and path is changed to sinusbot2 because I didn't want to destroy my original sinusbot container :D

**Comment by galexrt** [comment]
The `youtube-dl` problem has been fixed. The fixed images have been built and pushed.
Please repull the image and try again. :)

Thanks for your patience!

**Comment by MPK1** [comment]
I'll try it, thank you very much for your help.

**Comment by galexrt** [comment]
@MPK1 Please report back if it is working now.

**Comment by MPK1** [comment]
It seems like it's working perfectly, I looked at it only for a few seconds but it loads yt-dl just as it should.
