### ISSUE TITLE
Sinusbot password

### ISSUE THREAD

**Issue by seed1234** [galexrt/docker-sinusbot#19]
How do i get the sinusbot password

**Comment by galexrt** [comment]
You run `docker logs CONTAINER_NAME` and see the password in the logs.

**Comment by seed1234** [comment]
docker@box:~$ docker logs sinusbot
-> Setting Sinusbot log file location to "" ...
=> Sinusbot logging to "/sinusbot/data/sinus.log".
-> Updating sinusbot user and group id if necessary ...
-> Correcting file and mount point permissions ...
=> Corrected mount point permissions.
-> Checking if scripts directory is empty
=> Scripts directory is marked that scripts got copied. Nothing to do.
-> Checking for old data location ...
=> You are good to go! You are already using the new data directory, located at "/sinusbot/data".
=> Updating Youtube-dl...
youtube-dl is up-to-date (2017.03.10)
=> Updated youtube-dl with exit code 0
=> Starting SinusBot (https://sinusbot.com) by Michael Friese ...
 ___ ___ _  _ _   _ ___ ___  ___ _____  BETA
/ __|_ _| \| | | | / __| _ )/ _ \_   _|
\__ \| || .` | |_| \__ \ _ \ (_) || |
|___/___|_|\_|\___/|___/___/\___/ |_|

Version: 0.9.16-10f0fad
(C) 2013-2016 Michael Friese. All rights reserved.

Using Logfile /sinusbot/data/sinus.log
-> Setting Sinusbot log file location to "" ...
=> Sinusbot logging to "/sinusbot/data/sinus.log".
-> Updating sinusbot user and group id if necessary ...
-> Correcting file and mount point permissions ...
=> Corrected mount point permissions.
-> Checking if scripts directory is empty
=> Scripts directory is marked that scripts got copied. Nothing to do.
-> Checking for old data location ...
=> You are good to go! You are already using the new data directory, located at "/sinusbot/data".
=> Updating Youtube-dl...
youtube-dl is up-to-date (2017.03.10)
=> Updated youtube-dl with exit code 0
=> Starting SinusBot (https://sinusbot.com) by Michael Friese ...
 ___ ___ _  _ _   _ ___ ___  ___ _____  BETA
/ __|_ _| \| | | | / __| _ )/ _ \_   _|
\__ \| || .` | |_| \__ \ _ \ (_) || |
|___/___|_|\_|\___/|___/___/\___/ |_|

Version: 0.9.16-10f0fad
(C) 2013-2016 Michael Friese. All rights reserved.

Using Logfile /sinusbot/data/sinus.log
docker@box:~$

**Comment by seed1234** [comment]
I do not see any password

**Comment by galexrt** [comment]
I added instructions to the `README.md`, see https://github.com/galexrt/docker-sinusbot#normal.
Repull the image and run it again, then follow the instructions in the `README.md` (see the above link).

**Comment by seed1234** [comment]
i have re installed sinusbot 

i got the password, 

Thank you for your help

**Comment by galexrt** [comment]
@seed1234 What do you mean with "reinstalled sinusbot"?
Containers are not "reinstalled", but rerun/recreated..

**Comment by seed1234** [comment]
I have re created the sinusbot container
I could log in to Sinusbot Admin with no issues
I have changed password successfully

Now there is another issue, When i change the path of the files for sinnusbot/scripts and sinusbot/data
the sinusbot gui cannot log in as admin and keeps giving me unauthorized

http://imgur.com/a/jx3Rq
The image shows the containers path which i have not changed, but the left  field path is my path where i store all my docker files
I changed those and now it doesnt allow me to log in webGUI

**Comment by galexrt** [comment]
You have to move the files on the disk when you change the (host) path too.

**Comment by galexrt** [comment]
Closing as the main issue has been resolved. For your other issue you are having right now, it seems to be an issue related to your host setup. Just comment here and I'll try to help out a bit.

**Comment by galexrt** [comment]
@seed1234 Did you move the files on the disk too?
