### ISSUE TITLE
[Question] How to update the Docker image

### ISSUE THREAD

**Issue by vertipl** [galexrt/docker-sinusbot#20]
hello , can you update docker sinusbot becouse when i starting new instance i've got communication about update sinusbot.Thx

**Comment by galexrt** [comment]
You need to update the docker image.
The command to update the Docker image is:
```
docker pull quay.io/galexrt/sinusbot:latest
```
Or when using the Docker Hub image instead of the quay.io image:
```
docker pull galexrt/sinusbot:latest
```

**Comment by vertipl** [comment]
thx now it work
