### ISSUE TITLE
New version avaliable of sinusbot

### ISSUE THREAD

**Issue by RealRunSpace** [galexrt/docker-sinusbot#24]
Hello, there's a new version of SinusBot, how to update it? (Alredy pulled the image and restarted dockers)

**Comment by galexrt** [comment]
@RealRunSpace What version got released? The version in the image is `0.10.6-6b6bd3a`.

**Comment by RealRunSpace** [comment]
IDK but today is not working and it's saying I need to update in the logs

**Comment by galexrt** [comment]
@RealRunSpace You are using the `galexrt/sinusbot:latest` image, right?

**Comment by RealRunSpace** [comment]
Yep, I've copied & pasted it and restarted the docks

El 07/10/2017 13:32, "Alexander Trost" <notifications@github.com> escribió:

@RealRunSpace <https://github.com/realrunspace> You are using the
galexrt/sinusbot:latest image, right?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/galexrt/docker-sinusbot/issues/24#issuecomment-334928775>,
or mute the thread

**Comment by galexrt** [comment]
@RealRunSpace I tested both images (`galexrt/sinusbot:latest` and `quay.io/galexrt/sinusbot:latest`). Both are working.
Are you sure you have repulled the images correctly with `docker pull IMAGE_NAME`?

**Comment by RealRunSpace** [comment]
Used this command: docker pull quay.io/galexrt/sinusbot:latest

**Comment by galexrt** [comment]
Stop the sinusbot container, delete the sinusbot Docker image of your server and simply run the container again.

**Comment by RealRunSpace** [comment]
how do I delete the image? (Also, I will loose any data/music?)

**Comment by galexrt** [comment]
@RealRunSpace When you are using a volume for the container in the right place, no.
The command to remove images is: `docker rmi quay.io/galexrt/sinusbot:latest galexrt/sinusbot:latest`

**Comment by RealRunSpace** [comment]
ok, and now I just pull it again?

**Comment by RealRunSpace** [comment]
I started the container and still saying this:


```=> Updated youtube-dl with exit code 0
=> Starting SinusBot (https://sinusbot.com) by Michael Friese ...
This version has expired. Please download a newer version from the official SinusBot website and upgrade.
-> Updating sinusbot user and group id if necessary ...
-> Correcting file and mount point permissions ...
=> Corrected mount point permissions.
-> Checking if scripts directory is empty
=> Scripts directory is marked that scripts got copied. Nothing to do.
-> Checking for old data location ...
=> You are good to go! You are already using the new data directory, located at "/sinusbot/data".
=> Updating Youtube-dl...
youtube-dl is up-to-date (2017.10.07)
=> Updated youtube-dl with exit code 0
=> Starting SinusBot (https://sinusbot.com) by Michael Friese ...
This version has expired. Please download a newer version from the official SinusBot website and upgrade.```

**Comment by galexrt** [comment]
@RealRunSpace You simply run the container again. Does the same happen when you use `galexrt/sinusbot:latest` as the image?

**Comment by RealRunSpace** [comment]
yep, same error in all instances

**Comment by galexrt** [comment]
@RealRunSpace What is the output of `docker images` for the sinusbot image?

**Comment by RealRunSpace** [comment]
http://prntscr.com/guin20

**Comment by RealRunSpace** [comment]
Also, I want to say that thanks for your support again :)

**Comment by galexrt** [comment]
@RealRunSpace There seems to be something wrong with the way you pull the image. The image you have is 8 weeks old. The current one is about 4 days.

In your screenshot, the image has no tag which is weird. Please post the output of `docker pull galexrt/sinusbot:latest`. Make sure you use `galexrt/sinusbot:latest` as the image and not something else.

**Comment by RealRunSpace** [comment]
1. http://prntscr.com/guthm6
2. http://prntscr.com/guthtz
Now I have 2, but how do I delete the <no tag> one?

**Comment by RealRunSpace** [comment]
How do I change the image without loosing data? (As I have 2 containers)
http://prntscr.com/gutiat

**Comment by galexrt** [comment]
@RealRunSpace Just replace the image name in your docker run command.
Or do you use docker-compose?

**Comment by RealRunSpace** [comment]
I use this: 
`docker run --restart=always --name sinusbot8087 -d -v /opt/sinusbot/sinusbot8087:/sinusbot/data:z -p 8087:8087 galexrt/sinusbot:latest`

But I don't want a new docker, just update the image of the others one, and to start them I use docker start

**Comment by galexrt** [comment]
@RealRunSpace Are you sure that you used `galexrt/sinusbot:latest` as the image? From the `docker images` screenshot you hadn't used the tag.
When you really have used `-v ...:/sinusbot/data:z` you can simply stop, delete and run the container with the `latest` image. You shouldn't lose your data because of the Docker volume mount you use.

**Comment by RealRunSpace** [comment]
So to remove it I first kill the docker and them docker `container rm sinusbot8087,` and later which command do I use to create new docker containers for more instances?

**Comment by galexrt** [comment]
@RealRunSpace You stop the container, remove it with `docker rm CONTAINER_ID_OR_NAME` and then use your `docker run` command to start the container again.

I'm not going to provide any information on how to run more than one instance because that is against the license agreement of Sinusbot!

**Comment by RealRunSpace** [comment]
oh ok!

**Comment by galexrt** [comment]
@RealRunSpace Did this solve the issue for you? If so, please close this issue thanks!
If not please let me know how can help you further.

**Comment by RealRunSpace** [comment]
Thanks!
PD: why you don't have a [DONATE] button?
