### ISSUE TITLE
Question: Error when assign requested IP

### ISSUE THREAD

**Issue by DomBra** [galexrt/docker-sinusbot#26]
Hello,

I am not sure where I can ask those kind of questions. But when I open up the sinusbot with the `./entrypoint.sh` I get the Error 

```bash
listen tcp IP:PORT: bind: cannot assign requested address
```

What am I doing wrong? Could someone help me out?

**Comment by galexrt** [comment]
@DomBra What do you mean with "open up the sinusbot with the `./entrypoint.sh`"? Do you mean you start/run the container?

**Comment by DomBra** [comment]
@galexrt I have already started the container and than I run `./entrypoint.sh`, which results in this error.

**Comment by galexrt** [comment]
What is the output of `docker ps -a` and `ss -tulpn` on the host you Sinusbot on?
You just run the container and that starts the Sinusbot, no need to run any other command.

**Comment by DomBra** [comment]
Yes but how can I run multiple on multiple ports?

**Comment by galexrt** [comment]
@DomBra Running multiple Sinusbot is not allowed by the License Agreement/Terms of Service of Sinusbot. See https://wiki.sinusbot.com/en:info:licenses.

**Comment by DomBra** [comment]
Alright thanks for your help. It seems like the Sinusbot works now. Probably it was just an error on my side. Thanks for your help :)

**Comment by DomBra** [comment]
I have a follow up question. Maybe it is a bit simple, but what actually is the default login for the sinusbot?

**Comment by galexrt** [comment]
@DomBra The password will be displayed in the logs of the container on the first run, to get the logs run `docker logs CONTAINER_NAME_OR_ID`. If you didn't get the password, you have to delete the data directory of the container or follow the instructions below.

To manually override the password, you need to pull the latest image and add the `--override-password=newpassword` (where `newpassword` is your password of choice) as an argument to the end of your docker run command (example `docker run -d -p 8087:8087 galexrt/sinusbot:latest --override-password=newpassword`).
(See Sinusbot FAQ https://forum.sinusbot.com/faq/what-is-the-default-username-and-password.2/)

**Comment by DomBra** [comment]
One last question; I am not able to host my sinusbot on port `8087` is there any way to change the port to like `12345`? That would help me out very much thank you :)

**Comment by galexrt** [comment]
@DomBra You change the left port (host port) in your `docker run` command.
**Example**: To run the container on port `12345`, `docker run -d -p 12345:8087 ...`.
I suggest you checkout this Docker cheat sheet https://github.com/wsargent/docker-cheat-sheet which contains some help about this topic too.
