### ISSUE TITLE
Config should be editable

### ISSUE THREAD

**Issue by Horstexplorer** [galexrt/docker-sinusbot#33]
Hello,
if I would want to change the configuration file of the sinusbot, I would need to be root or at least sudo to edit the file and to install an editor. But it's not possible to change the user from Docker, or I couldnt figure out how to do it.

su --> must be run from a terminal
sudo -i --> unable to resolve host <dockername> + no tty present and no askpass program specified

**Comment by Horstexplorer** [comment]
Found out if i start the bash with --user root, it works but the other way may be better if u want to change it while working

**Comment by galexrt** [comment]
@Horstexplorer You shouldn't install an editor in the container.
A better way is to edit the config in the newly added `/sinusbot/config` volume, see updated README.md: https://github.com/galexrt/docker-sinusbot#mount-host-directory.
You have to add the new volume as written in the README.md and then after the first Sinusbot start, can edit the `config.ini` to suite your needs (don't forget to restart the container after config changes).

**Edit**: Updated the title as it is 100% intended to not run the container as root user, but as a low privileged normal user (uid 3000).
