### ISSUE TITLE
Sinusbot Youtube-DL slow

### ISSUE THREAD

**Issue by FabianSchurig** [galexrt/docker-sinusbot#37]
Hey there,

The youtube-dl as well as the youtube-dl-speedpatched are running very fast in the docker container but sadly they doesn't work fast with the sinusbot and its UI. 

In the UI it says download speed <400K/s and after some seconds it changes to 64K/s and then it changes some times between 0 and 64 till it stops after it has not more than 5mb downloaded . This equals the first 5mins of the 1hour track which i want to download.

Here a screenshot of the commands in the docker terminal:

![image](https://user-images.githubusercontent.com/11216482/41232531-f70f357c-6d86-11e8-9198-fa268df8cd1f.png)

Here a screenshot of the UI:

![image](https://user-images.githubusercontent.com/11216482/41232742-9adf0fec-6d87-11e8-8b86-f53353c1f5d3.png)

I also noticed that the sinusbot config.ini is not in the config folder `/sinusbot/config/config.ini` instead its directly in the `/sinusbot/config.ini`

Any hints which setting could be resulting in a slow download speed?

**Comment by galexrt** [comment]
@Bitfroest The `config.ini` is normally located at `/sinusbot/config.ini`. The `/sinusbot/config/` directory is just for the docker image to allow users to mount their own config file there which is then linked to `/sinusbot/config.ini`.

Are you on the latest image version? `docker image galexrt/sinusbot` can show you the image id/version.

**Comment by FabianSchurig** [comment]
Here is the result of `docker images galexrt/sinusbot`

![image](https://user-images.githubusercontent.com/11216482/41292403-c2af1cc6-6e52-11e8-8759-02fe678e73c4.png)

**Comment by galexrt** [comment]
@Bitfroest Could you try with the latest image (e.g. `docker pull galexrt/sinusbot:latest`).
This assumes you are using the Docker Hub image and not Quay.io image.

**Comment by galexrt** [comment]
Closing as there has been no response and my Sinusbot instance downloads everything almost instantly.
