### ISSUE TITLE
Chat problems

### ISSUE THREAD

**Issue by peralta00** [galexrt/docker-sinusbot#45]
Hi guys, am i the only one with problems regarding chat commands ?
the bot doesnt respond to any command, Ex: !yt or !ytdl

**Comment by galexrt** [comment]
If Sinusbot is connected to your TeamSpeak server, it is probably a question of the instance commands settings. Are your permissions in Sinusbot and/or the Sinusbot user correct?

Also are you on the latest Sinusbot Docker image? Maybe there has been a fix in Sinusbot.

**Comment by peralta00** [comment]
Permissions are all right and the image was the latest when i submited the issue.
I dont know how but it is working again :P .

Thanks Anyway !
