### ISSUE TITLE
!yt command not working

### ISSUE THREAD

**Issue by RealRunSpace** [galexrt/docker-sinusbot#46]
Hello, I'm trying to use this command `!yt https://www.youtube.com/watch?v=E8VwtjhMFJ8` and I get this in the logs (and no music playing) `2019/03/08 23:15:55 cc7fbda3 7868d07b INFO   PRIVATE-CHAT [RealRunSpace] yt [URL]https://www.youtube.com/watch?v=E8VwtjhMFJ8[/URL]
2019/03/08 23:15:55 cc7fbda3 7868d07b INFO   CHAT 1 [rrs @ RealRunSpace] < yt [URL]https://www.youtube.com/watch?v=E8VwtjhMFJ8[/URL] > / OK
2019/03/08 23:15:59 err from ytdl: exit status 1`
I don't see any error log for ytdl, so I don't really know what's wrong. I'm using Centos7 with CWP + Firewall.

**Comment by RealRunSpace** [comment]
also there's no config.ini file in /opt/docker/sinusbot/config/ directory

**Comment by RealRunSpace** [comment]
updating ytdl fixed it

**Comment by galexrt** [comment]
@RealRunSpace I have pushed an updated image, which should include the latest Sinusbot and YoutubeDL. So repulling the image should do the trick, if you are using my image from Docker Hub or Quay.

**Comment by RealRunSpace** [comment]
Ok, thanks!
