### ISSUE TITLE
Docker problem whit connect to localhost

### ISSUE THREAD

**Issue by dragoslavdamjanovic** [galexrt/docker-sinusbot#5]
You see like  that everywhere can that connects music bot just can not to localhost ip if we write Instance-Log : 2016-03-22T19:18:49+01:00 TSClient quit. 
but only in the localhost

**Comment by galexrt** [comment]
You try to connect from the sinusbot to localhost as the server address?

**Comment by dragoslavdamjanovic** [comment]
Sinusbot when I install we're working on localhost and when I install Docke not that we connect to localhost

**Comment by galexrt** [comment]
@dragoslavdamjanovic Please provide the docker version you are using.
What do you mean by "when I install Docke not that we connect to localhost"?
Does sinusbot have an  error?

**Comment by dragoslavdamjanovic** [comment]
https://www.youtube.com/watch?v=75EjFf-80uE that version :) 
I went on these installations other VPS connect but only not connect localhost :/ 016-03-22T19:15:07+01:00 Starting instance ts3server://ts.skup-ludaka.info.tm?port=9988&nickname=Proba%202&password=&channel=&channelpassword=
2016-03-22T19:18:49+01:00 KILL [admin] OK
2016-03-22T19:18:49+01:00 TSClient quit.

**Comment by dragoslavdamjanovic** [comment]
2016-03-22T20:18:00+01:00 Starting instance ts3server://127.0.0.1?port=9996&nickname=Proba%202&password=&channel=&channelpassword=
2016-03-22T22:47:23+01:00 KILL [admin] OK
2016-03-22T22:47:23+01:00 TSClient quit.

**Comment by galexrt** [comment]
@dragoslavdamjanovic The Docker image in the video is `VeltroGaming/sinusbot` not `galexrt/docker-sinusbot`.

In the comments on the video it is mentioned, that `127.0.0.1` can't be used as the teamspeak server address to connect to your teamspeak server, try to use the public teamspeak server ip.

**Comment by dragoslavdamjanovic** [comment]
how do you think the public? IP from VPS?

**Comment by dragoslavdamjanovic** [comment]
a right has a version that can be on the localhost

**Comment by galexrt** [comment]
public IP = ip from VPS

**Comment by dragoslavdamjanovic** [comment]
will not that

**Comment by dragoslavdamjanovic** [comment]
I can send data panel on email

**Comment by dragoslavdamjanovic** [comment]
but to see

**Comment by dragoslavdamjanovic** [comment]
How to kill docker??

**Comment by galexrt** [comment]
Why would you want to kill Docker?

**Comment by dragoslavdamjanovic** [comment]
but I deleted folders and he still works So how do I turn bota

**Comment by dragoslavdamjanovic** [comment]
would want to kill Docker when I can on connect to localhost :)

**Comment by raaaimund** [comment]
If you say "connect to localhost" - is the bot trying to connect to the host machine or to its docker container?
I think it is trying to connect to 127.0.0.1 of your container and not to your host machine where your teamspeak server is running.
Or am I wrong?

**Comment by dragoslavdamjanovic** [comment]
I can not 127.0.0.1 or via ip machines I can not not via domainsm ,on the other wants connect all the normal ... only on the runway, where it will install

**Comment by raaaimund** [comment]
I had the same problem.
Could not connect to my teamspeak server which is running in another container - I updated Docker with `apt-get update` (or an other package manager) and restarted my machine. After this update everything worked as expected.

**Comment by dragoslavdamjanovic** [comment]
breakthrough has no chance

**Comment by galexrt** [comment]
@dragoslavdamjanovic Have you restarted your vps and tried again?

**Comment by galexrt** [comment]
**PLEASE NOTE**: As I noticed you followed a tutorial, you should know what commands you ran and what they do. If you don't know what you are doing when following a tutorial, you are doing it completely wrong!
You have to inform yourself what the commands do you run, to understand why in this case there was a problem with connecting, problems that may occur later on.

**Comment by dragoslavdamjanovic** [comment]
So how do I clear it

**Comment by galexrt** [comment]
@dragoslavdamjanovic What do you mean by "clear it"?

**Comment by dragoslavdamjanovic** [comment]
Look doing everything nice Only what can not link vps where I installed

**Comment by galexrt** [comment]
@dragoslavdamjanovic What is the hostname of the vps?

**Comment by dragoslavdamjanovic** [comment]
tse-traileu

**Comment by raaaimund** [comment]
You mean http://www.e-trail.eu/?
You could try to determine your problem by creating a new bash session. 

You can create a new bash session with this command:
`docker exec -i -t <nameofcontainer> bash`
[https://docs.docker.com/engine/reference/commandline/exec/](url)

Maybe this helps you to determine, whats going on.

**Comment by galexrt** [comment]
Closing as the question seems to be answered.
