### ISSUE TITLE
TS3 Client Update

### ISSUE THREAD

**Issue by Finch-Tamo** [galexrt/docker-sinusbot#6]
Hi, 
Can you update the ts3-client to 3.0.19 please; thx ! ;)

**Comment by galexrt** [comment]
@Finch29 See this issue https://github.com/VeltroGaming/sinusbot/issues/4.
When the above issue is resolved, I can update the ts3 client to the latest version.
The sinusbot is still usable with the current ts3 client version.

**Comment by galexrt** [comment]
@Finch29 Good news. I just pushed the updated version with ts3 client version 3.0.19.
