### ISSUE TITLE
User UID should be configurable

### ISSUE THREAD

**Issue by Samistine** [galexrt/docker-sinusbot#7]
User UID should be configurable

**Comment by galexrt** [comment]
I added this feature.
You can now use the `SINUS_USER` and `SINUS_GROUP` environment variables to change the UID.

**Comment by galexrt** [comment]
You should be able to pull the updated version in the next few minutes.
Have Fun!
P.S. If you need any other features, please let me know so I can try my best to help you.

**Comment by galexrt** [comment]
BTW I have seen you adding a link to the `scripts/` folder.
I have now added this feature too. The `scripts/` folder will now be linked to the data directory/folder.
